# Generated by Django 4.0 on 2021-12-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('slug', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productdetail')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='main.seller')),
            ],
        ),
    ]
