# Generated by Django 4.0 on 2022-06-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[(5, 'Five Stars'), (4, 'Four Stars'), (3, 'Three Stars'), (2, 'Two Stars'), (1, 'One Star')], max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
