# Generated by Django 4.0 on 2022-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, 'One Star')], max_length=255),
        ),
    ]
